/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GerenciadorDeInterfaceGrafica;

import GerenciadorDeTarefas.GerenciadorInterfaceGrafica;
import GerenciadorDeTarefas.Uteis;
import Modelos.Servico;
import java.awt.Color;
import java.text.ParseException;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;

/**
 *
 * @author luizn
 */
public class FormServicos extends javax.swing.JFrame {

    private GerenciadorInterfaceGrafica gerenciador;
    
    public FormServicos(GerenciadorInterfaceGrafica gerenciador) {
        initComponents();
        setResizable(false); 
        this.gerenciador = gerenciador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadastro = new javax.swing.JPanel();
        labelDescricao = new javax.swing.JLabel();
        inputDescricao = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        inputValor = new javax.swing.JTextField();
        labelValor = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        inputNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(250, 200));

        jPanelCadastro.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCadastro.setMaximumSize(new java.awt.Dimension(350, 300));
        jPanelCadastro.setMinimumSize(new java.awt.Dimension(350, 300));
        jPanelCadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelDescricao.setText("Descrição");
        jPanelCadastro.add(labelDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 52, -1, -1));
        jPanelCadastro.add(inputDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 48, 141, -1));

        labelNome.setText("Nome");
        jPanelCadastro.add(labelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 10, -1, -1));
        jPanelCadastro.add(inputValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 86, 141, -1));

        labelValor.setText("Valor");
        jPanelCadastro.add(labelValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 90, 50, -1));

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelCadastro.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 128, 254, 52));
        jPanelCadastro.add(inputNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 6, 141, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if ( validarCampos()){ 
            try {
                gerenciador.getGerenciador_dominio().inserirServico(
                    inputNome.getText(),
                    inputDescricao.getText(),
                    Float.parseFloat(inputValor.getText()
                ));  

                gerenciador.carregarComboBoxCadastro(Servico.class);
                JOptionPane.showMessageDialog(rootPane, "Serviço Cadastrado com Sucesso!");

            }catch(HibernateException ex){
                JOptionPane.showMessageDialog(rootPane, "Error ao Cadastrar Serviço");
            }                   
            this.setVisible(false);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private boolean validarCampos() { 
        String msgErro = "";
        
        labelNome.setForeground(Color.black);
        labelDescricao.setForeground(Color.black); 
        labelValor.setForeground(Color.black);
        Float valor;
        try {                
            if ( inputNome.getText().isEmpty() ) {
                msgErro = msgErro + "Digite seu nome.\n";
                labelNome.setForeground(Color.red);            
            }

            if ( inputDescricao.getText().isEmpty() ) {
                msgErro = msgErro + "Digite seu Telefone.\n";
                labelDescricao.setForeground(Color.red);            
            }

            if ( inputValor.getText().isEmpty() ) {
                msgErro = msgErro + "Digite o valor do Serviço.\n";
                labelValor.setForeground(Color.red);            
            }
            valor = Float.parseFloat(inputValor.getText());
            if ( valor < 0 ) {
                msgErro = msgErro + "Digite um valor Válido";
                labelValor.setForeground(Color.red);            
            }        
        }catch (NumberFormatException e) { 
                JOptionPane.showMessageDialog(rootPane, "Digite um valor Válido.");
            } 
        
        
        
        if ( msgErro.isEmpty() ) {
            return true;
        } else {            
            JOptionPane.showMessageDialog(this, msgErro, "ERRO Cliente", JOptionPane.ERROR_MESSAGE  );
            return false;
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputDescricao;
    private javax.swing.JTextField inputNome;
    private javax.swing.JTextField inputValor;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanelCadastro;
    private javax.swing.JLabel labelDescricao;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelValor;
    // End of variables declaration//GEN-END:variables
}
